import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: theme.card,
        width: '90%',
        maxWidth: 600,
        maxHeight: '85%',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        overflow: 'hidden',
    },
    modalHeader: {
        paddingVertical: 24,
        paddingHorizontal: 32,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
        flexDirection: 'column',
        alignItems: 'stretch',
        backgroundColor: theme.card,
        zIndex: 10,
    },
    headerTopRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    headerBottomRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
        gap: 12,
    },
    headerTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 24,
        color: theme.text,
    },
    headerSubtitle: {
        flex: 1,
        color: theme.textSecondary,
        fontSize: 13.6,
        fontFamily: 'Inter_400Regular',
    },
    dateBadge: {
        backgroundColor: '#F7FAFC',
        borderWidth: 1,
        borderColor: theme.border,
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    dateBadgeText: {
        fontSize: 12.8,
        fontWeight: '600',
        color: 'black',
        fontFamily: 'Inter_600SemiBold',
    },
    closeBtn: {
        padding: 4,
    },
    modalBody: {
        padding: 32,
        backgroundColor: theme.card,
    },
    modalBodyContent: {
        gap: 24,
        paddingBottom: 32,
    },
    checkinCard: {
        backgroundColor: theme.card,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 12,
        padding: 24,
        width: '100%',
    },
    checkinCardFeatured: {
        borderWidth: 2,
        borderColor: '#7C9A92',
    },
    badgeFeatured: {
        position: 'absolute',
        top: -12,
        alignSelf: 'center',
        backgroundColor: '#7C9A92',
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 12,
    },
    badgeFeaturedText: {
        color: 'white',
        fontSize: 11.2,
        fontWeight: '700',
        textTransform: 'uppercase',
        fontFamily: 'Inter_700Bold',
    },
    cardHeader: {
        marginBottom: 20,
    },
    cardHeaderTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    cardHeaderTitleText: {
        fontSize: 17.6,
        fontWeight: '600',
        color: theme.text,
        fontFamily: 'Inter_600SemiBold',
    },
    cardHeaderTitleTextFeatured: {
        color: '#7C9A92',
    },
    stepNum: {
        backgroundColor: '#F7FAFC',
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepNumFeatured: {
        backgroundColor: '#7C9A92',
    },
    stepNumText: {
        color: theme.textSecondary,
        fontSize: 12.8,
        fontWeight: '700',
        fontFamily: 'Inter_700Bold',
    },
    stepNumTextFeatured: {
        color: 'white',
    },
    cardHeaderSubtitle: {
        fontSize: 13.6,
        color: theme.textSecondary,
        paddingTop: 4,
        paddingLeft: 8,
        fontFamily: 'Inter_400Regular',
    },
    numOptionRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginVertical: 20,
    },
    numButton: {
        width: 35,
        height: 35,
        borderRadius: 17.5,
        borderWidth: 1,
        borderColor: '#ddd',
        backgroundColor: theme.card,
        alignItems: 'center',
        justifyContent: 'center',
    },
    numButtonSelected: {
        borderWidth: 2,
        borderColor: '#7C9A92',
        backgroundColor: '#7C9A92',
    },
    numButtonText: {
        color: theme.textSecondary,
        fontFamily: 'Inter_400Regular',
    },
    numButtonTextSelected: {
        color: 'white',
        fontWeight: 'bold',
        fontFamily: 'Inter_700Bold',
    },
    numOptionLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    numOptionLabelText: {
        fontSize: 11,
        color: '#777',
        fontFamily: 'Inter_400Regular',
    },
    checklist: {
        marginTop: 15,
        gap: 12,
    },
    checklistItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginBottom: 8,
    },
    checklistLabel: {
        fontSize: 15.2,
        color: theme.text,
        fontFamily: 'Inter_400Regular',
    },
    checklistLabelBold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: 'bold',
    },
    notesArea: {
        width: '100%',
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 8,
        padding: 12,
        fontFamily: 'Inter_400Regular',
        fontSize: 15.2,
        minHeight: 120,
        backgroundColor: '#F7FAFC',
        textAlignVertical: 'top',
    },
    modalFooter: {
        paddingVertical: 16,
        paddingHorizontal: 20,
        borderTopWidth: 1,
        borderTopColor: theme.border,
        backgroundColor: theme.card,
        width: '100%',
    },
    footerButtons: {
        flexDirection: 'row',
        width: '100%',
        justifyContent: 'space-between',
        gap: 12,
    },
    btnOutline: {
        flex: 1,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: theme.border,
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnOutlineText: {
        color: theme.text,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
    },
    btnPrimary: {
        flex: 1,
        backgroundColor: '#7C9A92',
        paddingVertical: 12,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnPrimaryDisabled: {
        opacity: 0.6,
    },
    btnPrimaryText: {
        color: 'white',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14.4,
    },
    radioCircle: {
        width: 18,
        height: 18,
        borderRadius: 9,
        borderWidth: 2,
        borderColor: theme.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    radioCircleSelected: {
        borderColor: '#7C9A92',
    },
    radioDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#7C9A92',
    },
    checkbox: {
        width: 18,
        height: 18,
        borderWidth: 2,
        borderColor: theme.border,
        borderRadius: 4,
        alignItems: 'center',
        justifyContent: 'center',
    },
    checkboxSelected: {
        backgroundColor: '#7C9A92',
        borderColor: '#7C9A92',
    },
    keyboardAvoidingView: {
        width: '100%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconTimes: {
        fontSize: 16,
    },
    iconCalendar: {
        fontSize: 12,
        color: 'black',
    },
    checklistMargin: {
        marginBottom: 20,
    },
    iconCheck: {
        fontSize: 10,
        color: 'white',
    }
});
