import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#FFFFFF',
        width: '90%',
        maxWidth: 600,
        maxHeight: '85%',
        borderRadius: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
        overflow: 'hidden',
    },
    modalHeader: {
        paddingVertical: 24,
        paddingHorizontal: 32,
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
    },
    headerTextContainer: {
        flex: 1,
    },
    headerTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 24,
        color: '#2D3748',
        marginBottom: 4,
    },
    headerSubtitle: {
        color: '#718096',
        fontSize: 14.4,
        fontFamily: 'Inter_400Regular',
    },
    closeBtn: {
        padding: 4,
        marginLeft: 16,
    },
    modalBody: {
        padding: 32,
        backgroundColor: '#FAFAFA',
    },
    modalBodyContent: {
        gap: 24,
        paddingBottom: 32,
    },
    feedbackCard: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 12,
        padding: 24,
        width: '100%',
    },
    cardHeader: {
        marginBottom: 16,
    },
    cardHeaderCenter: {
        alignItems: 'center',
    },
    cardHeaderTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 4,
    },
    cardHeaderTitleText: {
        fontSize: 17.6,
        fontWeight: '600',
        color: '#2D3748',
        fontFamily: 'Inter_600SemiBold',
    },
    cardHeaderSubtitle: {
        fontSize: 13.6,
        color: '#718096',
        paddingTop: 4,
        paddingLeft: 8,
        fontFamily: 'Inter_400Regular',
    },
    cardHeaderSubtitleCenter: {
        paddingLeft: 0,
        textAlign: 'center',
    },
    stepNum: {
        backgroundColor: '#F7FAFC',
        width: 24,
        height: 24,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepNumText: {
        color: '#718096',
        fontSize: 12.8,
        fontWeight: '700',
        fontFamily: 'Inter_700Bold',
    },
    starRating: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: 12,
        marginVertical: 15,
    },
    starIcon: {
        padding: 5,
    },
    chipGroup: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
        marginTop: 10,
    },
    chipLabel: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        backgroundColor: '#F7FAFC',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 20,
    },
    chipLabelSelected: {
        backgroundColor: '#7C9A92',
        borderColor: '#7C9A92',
    },
    chipText: {
        fontSize: 13.6,
        color: '#2D3748',
        fontFamily: 'Inter_400Regular',
    },
    chipTextSelected: {
        color: '#FFFFFF',
    },
    textArea: {
        width: '100%',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 8,
        padding: 12,
        fontFamily: 'Inter_400Regular',
        fontSize: 15.2,
        minHeight: 100,
        backgroundColor: '#F7FAFC',
        textAlignVertical: 'top',
    },
    textAreaFocused: {
        borderColor: '#7C9A92',
        backgroundColor: '#FFFFFF',
    },
    modalFooter: {
        paddingVertical: 20,
        paddingHorizontal: 32,
        borderTopWidth: 1,
        borderTopColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
    },
    footerButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    btnOutline: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        paddingVertical: 10,
        paddingHorizontal: 20,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnOutlineText: {
        color: '#2D3748',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14.4,
    },
    btnPrimary: {
        backgroundColor: '#7C9A92',
        paddingVertical: 10,
        paddingHorizontal: 24,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnPrimaryText: {
        color: 'white',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14.4,
    },
});
