import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.card, position: 'relative' },
    bgBlob: { position: 'absolute', width: 700, height: 700, borderRadius: 350, bottom: -200, left: -150, opacity: 0.6 },
    scrollContent: { paddingTop: 20, paddingBottom: 20, alignItems: 'center' },
    card: {
        backgroundColor: theme.card, paddingHorizontal: 24, width: '100%', maxWidth: 520,
    },
    brandContainer: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', marginBottom: 24, gap: 10 },
    brandText: { fontFamily: 'Merriweather_700Bold', fontSize: 22.4, color: theme.text },
    header: { alignItems: 'center', marginBottom: 24 },
    headerTitle: { fontFamily: 'Merriweather_700Bold', fontSize: 28, color: theme.text, marginBottom: 8, textAlign: 'center' },
    headerSubtitle: { fontFamily: 'Inter_400Regular', fontSize: 15.2, color: theme.textSecondary, textAlign: 'center' },
    sectionTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 17.6, color: theme.text, marginBottom: 15 },
    formRow: { flexDirection: 'row', width: '100%', justifyContent: 'space-between' },
    formGroup: { marginBottom: 16 },
    label: { fontFamily: 'Inter_600SemiBold', fontSize: 13.6, color: theme.text, marginBottom: 8 },
    input: { fontFamily: 'Inter_400Regular', backgroundColor: theme.background, borderWidth: 1, borderColor: theme.border, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, fontSize: 16, color: theme.text },
    dropdownInput: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: theme.background, borderWidth: 1, borderColor: theme.border, borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: theme.card, borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 20, paddingBottom: 40, maxHeight: '80%', borderWidth: 2, borderColor: theme.border },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: theme.border, marginBottom: 8 },
    modalTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 18, color: theme.text },
    dropdownItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#F7FAFC' },
    dropdownItemSelected: { backgroundColor: '#F0F5F4', borderRadius: 8, paddingHorizontal: 12 },
    dropdownItemText: { fontFamily: 'Inter_400Regular', fontSize: 16, color: theme.text },
    dropdownItemTextSelected: { fontFamily: 'Inter_600SemiBold', color: '#7C9A92' },
    dividerLine: { height: 1, backgroundColor: theme.border, marginVertical: 20 },
    checkboxRow: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 12 },
    checkboxLabel: { fontFamily: 'Inter_400Regular', marginLeft: 12, fontSize: 13.6, color: theme.textSecondary, flex: 1, marginTop: 2, lineHeight: 18 },
    errorText: { fontFamily: 'Inter_600SemiBold', color: theme.danger, fontSize: 14.4, textAlign: 'center', marginVertical: 10 },
    submitBtn: { width: '100%', backgroundColor: '#7C9A92', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginTop: 10, marginBottom: 24 },
    submitBtnDisabled: { opacity: 0.5 },
    submitBtnText: { fontFamily: 'Inter_600SemiBold', color: theme.card, fontSize: 16 },
    footerLinks: { flexDirection: 'row', justifyContent: 'center' },
    footerText: { fontFamily: 'Inter_400Regular', color: theme.textSecondary, fontSize: 14.4 },
    linkText: { fontFamily: 'Inter_600SemiBold', color: '#7C9A92', fontSize: 14.4, textDecorationLine: 'underline', },
    dropdownLabelActive: { color: '#2D3748' },
    dropdownLabelInactive: { color: '#A0AEC0' },
    iconChevron: { fontSize: 20 },
    iconCheckmark: { fontSize: 20, color: '#7C9A92' },
    iconHeartPulse: { fontSize: 22, color: '#7C9A92' },
    iconCheckboxChecked: { color: '#7C9A92', fontSize: 22 },
    iconCheckboxUnchecked: { color: '#718096', fontSize: 22 },
    formGroupHalf: { width: '48%' },
    formGroupHalfMarginTop: { width: '48%', marginTop: 18 },
    flex1: { flex: 1 },
    footerLinksBottom: { marginBottom: 10 }
});
