import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC', // Matching var(--bg-body)
    },
    mainContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 40,
    },
    header: {
        marginBottom: 20,
    },
    title: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 24,
        color: '#2D3748',
    },
    subtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: '#718096',
        marginTop: 4,
    },
    notEnoughDataContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        marginBottom: 30,
        marginTop: 20,
    },
    notEnoughDataIcon: {
        marginBottom: 20,
    },
    notEnoughDataTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 22,
        color: '#2D3748',
        marginBottom: 15,
        textAlign: 'center',
    },
    notEnoughDataDesc: {
        fontFamily: 'Inter_400Regular',
        fontSize: 15,
        color: '#718096',
        textAlign: 'center',
        lineHeight: 22,
    },
    boldDesc: {
        fontFamily: 'Inter_600SemiBold',
        color: '#2D3748',
    },
    baselineHeader: {
        marginTop: 30,
        marginBottom: 15,
    },
    baselineTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 20,
        color: '#2D3748',
    },
    baselineDesc: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: '#718096',
        marginTop: 4,
    },
    metricCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        marginBottom: 15,
    },
    cardTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    iconBg: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardLabel: {
        fontFamily: 'Inter_500Medium',
        fontSize: 14,
        color: '#718096',
    },
    cardValue: {
        fontFamily: 'Inter_700Bold',
        fontSize: 28,
        color: '#2D3748',
        marginVertical: 5,
    },
    trendBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        gap: 4,
    },
    trendUp: {
        backgroundColor: '#D1FAE5',
    },
    trendDown: {
        backgroundColor: '#FEE2E2',
    },
    trendTextUp: {
        color: '#10B981',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    trendTextDown: {
        color: '#EF4444',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    chartContainer: {
        width: '100%',
        height: 180,
        marginTop: 20,
        marginBottom: 15,
        position: 'relative',
    },
    chartXAxis: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 5,
    },
    chartXAxisText: {
        color: '#A0AEC0',
        fontFamily: 'Inter_400Regular',
        fontSize: 10,
    },
    chartTooltip: {
        position: 'absolute',
        backgroundColor: '#2D3748',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
        zIndex: 10,
    },
    chartTooltipText: {
        color: '#FFFFFF',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    chartTooltipDot: {
        position: 'absolute',
        width: 12,
        height: 12,
        backgroundColor: '#FFFFFF',
        borderColor: '#5B8DEF',
        borderWidth: 3,
        borderRadius: 6,
        zIndex: 10,
    },
    maslowVisual: {
        flexDirection: 'column-reverse', // Pyramids are built from bottom
        gap: 8,
        marginBottom: 20,
    },
    maslowLevel: {
        width: '100%',
        paddingVertical: 12,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    maslowTextActive: {
        color: '#FFFFFF',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
    },
    maslowTextInactive: {
        color: '#FFFFFF',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        opacity: 0.8,
    },
    insightBox: {
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        padding: 12,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: '#10B981',
        marginTop: 10,
    },
    insightBoxTitle: {
        color: '#059669',
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        marginBottom: 4,
    },
    insightBoxText: {
        color: '#2D3748',
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
    },
    interactiveRow: {
        backgroundColor: '#F8FAFC',
        padding: 12,
        borderRadius: 10,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    interactiveRowIconBox: {
        minWidth: 40,
        height: 40,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    interactiveRowContent: {
        flex: 1,
    },
    interactiveRowLabel: {
        fontFamily: 'Inter_400Regular',
        fontSize: 12,
        color: '#718096',
        marginBottom: 2,
    },
    interactiveRowText: {
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: '#2D3748',
        lineHeight: 18,
    },
    interactiveRowTextBold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: 'bold',
        color: '#2D3748',
    },
    riskScoreContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
        marginTop: 10,
    },
    riskScoreValue: {
        fontFamily: 'Inter_700Bold',
        fontSize: 40,
    },
    riskScoreDesc: {
        flex: 1,
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: '#718096',
        lineHeight: 18,
    },
    progressTrack: {
        width: '100%',
        backgroundColor: '#E2E8F0',
        height: 12,
        borderRadius: 6,
        marginTop: 20,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        borderRadius: 6,
    },
    concernsList: {
        marginTop: 15,
        gap: 12,
    },
    concernRow: {
        backgroundColor: '#F8FAFC',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderLeftWidth: 4,
    },
    concernRowConcerning: {
        borderLeftColor: '#EF4444',
    },
    concernRowHealthy: {
        borderLeftColor: '#10B981',
    },
    concernTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        color: '#2D3748',
    },
    concernSubtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 12,
        color: '#718096',
        marginTop: 2,
    },
    concernBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 20,
    },
    badgeConcerning: {
        backgroundColor: '#FEE2E2',
    },
    badgeHealthy: {
        backgroundColor: '#D1FAE5',
    },
    badgeTextConcerning: {
        color: '#EF4444',
        fontFamily: 'Inter_700Bold',
        fontSize: 11,
    },
    badgeTextHealthy: {
        color: '#10B981',
        fontFamily: 'Inter_700Bold',
        fontSize: 11,
    }
});
