import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.background, // Matching var(--bg-body)
    },
    mainContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 40,
    },
    header: {
        marginBottom: 20,
    },
    title: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 24,
        color: theme.text,
    },
    subtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: theme.textSecondary,
        marginTop: 4,
    },
    notEnoughDataContainer: {
        backgroundColor: theme.card,
        borderRadius: 16,
        padding: 40,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: theme.border,
        marginBottom: 30,
        marginTop: 20,
    },
    notEnoughDataIcon: {
        marginBottom: 20,
    },
    notEnoughDataTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 22,
        color: theme.text,
        marginBottom: 15,
        textAlign: 'center',
    },
    notEnoughDataDesc: {
        fontFamily: 'Inter_400Regular',
        fontSize: 15,
        color: theme.textSecondary,
        textAlign: 'center',
        lineHeight: 22,
    },
    boldDesc: {
        fontFamily: 'Inter_600SemiBold',
        color: theme.text,
    },
    baselineHeader: {
        marginTop: 30,
        marginBottom: 15,
    },
    baselineTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 20,
        color: theme.text,
    },
    baselineDesc: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: theme.textSecondary,
        marginTop: 4,
    },
    metricCard: {
        backgroundColor: theme.card,
        borderRadius: 20,
        padding: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 3,
        marginBottom: 15,
    },
    cardTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    iconBg: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardLabel: {
        fontFamily: 'Inter_500Medium',
        fontSize: 14,
        color: theme.textSecondary,
    },
    cardValue: {
        fontFamily: 'Inter_700Bold',
        fontSize: 28,
        color: theme.text,
        marginVertical: 5,
    },
    trendBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 4,
        paddingHorizontal: 8,
        borderRadius: 6,
        gap: 4,
    },
    trendUp: {
        backgroundColor: '#D1FAE5',
    },
    trendDown: {
        backgroundColor: '#FEE2E2',
    },
    trendTextUp: {
        color: theme.primary,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    trendTextDown: {
        color: theme.danger,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    chartContainer: {
        width: '100%',
        height: 180,
        marginTop: 20,
        marginBottom: 15,
        position: 'relative',
    },
    chartXAxis: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 5,
    },
    chartXAxisText: {
        color: '#A0AEC0',
        fontFamily: 'Inter_400Regular',
        fontSize: 10,
    },
    chartTooltip: {
        position: 'absolute',
        backgroundColor: theme.text,
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 8,
        zIndex: 10,
    },
    chartTooltipText: {
        color: theme.card,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
    },
    chartTooltipDot: {
        position: 'absolute',
        width: 12,
        height: 12,
        backgroundColor: theme.card,
        borderColor: '#5B8DEF',
        borderWidth: 3,
        borderRadius: 6,
        zIndex: 10,
    },
    maslowVisual: {
        flexDirection: 'column-reverse', // Pyramids are built from bottom
        gap: 8,
        marginBottom: 20,
    },
    maslowLevel: {
        width: '100%',
        paddingVertical: 12,
        borderRadius: 6,
        alignItems: 'center',
        justifyContent: 'center',
    },
    maslowTextActive: {
        color: theme.card,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
    },
    maslowTextInactive: {
        color: theme.card,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        opacity: 0.8,
    },
    insightBox: {
        backgroundColor: 'rgba(16, 185, 129, 0.15)',
        padding: 12,
        borderRadius: 12,
        borderLeftWidth: 4,
        borderLeftColor: theme.primary,
        marginTop: 10,
    },
    insightBoxTitle: {
        color: theme.primary,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        marginBottom: 4,
    },
    insightBoxText: {
        color: theme.text,
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
    },
    interactiveRow: {
        backgroundColor: theme.background,
        padding: 12,
        borderRadius: 10,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    interactiveRowIconBox: {
        minWidth: 40,
        height: 40,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    interactiveRowContent: {
        flex: 1,
    },
    interactiveRowLabel: {
        fontFamily: 'Inter_400Regular',
        fontSize: 12,
        color: theme.textSecondary,
        marginBottom: 2,
    },
    interactiveRowText: {
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: theme.text,
        lineHeight: 18,
    },
    interactiveRowTextBold: {
        fontFamily: 'Inter_700Bold',
        fontWeight: 'bold',
        color: theme.text,
    },
    riskScoreContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 15,
        marginTop: 10,
    },
    riskScoreValue: {
        fontFamily: 'Inter_700Bold',
        fontSize: 40,
    },
    riskScoreDesc: {
        flex: 1,
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: theme.textSecondary,
        lineHeight: 18,
    },
    progressTrack: {
        width: '100%',
        backgroundColor: theme.border,
        height: 12,
        borderRadius: 6,
        marginTop: 20,
        overflow: 'hidden',
    },
    progressFill: {
        height: '100%',
        borderRadius: 6,
    },
    concernsList: {
        marginTop: 15,
        gap: 12,
    },
    concernRow: {
        backgroundColor: theme.background,
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderLeftWidth: 4,
    },
    concernRowConcerning: {
        borderLeftColor: theme.danger,
    },
    concernRowHealthy: {
        borderLeftColor: theme.primary,
    },
    concernTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        color: theme.text,
    },
    concernSubtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 12,
        color: theme.textSecondary,
        marginTop: 2,
    },
    concernBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 20,
    },
    badgeConcerning: {
        backgroundColor: '#FEE2E2',
    },
    badgeHealthy: {
        backgroundColor: '#D1FAE5',
    },
    badgeTextConcerning: {
        color: theme.danger,
        fontFamily: 'Inter_700Bold',
        fontSize: 11,
    },
    badgeTextHealthy: {
        color: theme.primary,
        fontFamily: 'Inter_700Bold',
        fontSize: 11,
    },
    concernFlex: {
        flex: 1,
        paddingRight: 10,
    },
    loadingContainer: {
        justifyContent: 'center',
        alignItems: 'center',
    },
    heartIconBg: {
        backgroundColor: 'rgba(236, 72, 153, 0.1)',
    },
    chartToggleContainer: {
        flexDirection: 'row',
        width: '100%',
        gap: 10,
        marginVertical: 15,
    },
    chartToggleBtnActive7: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 20,
        alignItems: 'center',
        backgroundColor: '#5B8DEF',
    },
    chartToggleBtnActive30: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 20,
        alignItems: 'center',
        backgroundColor: '#10B981',
    },
    chartToggleBtnInactive: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 20,
        alignItems: 'center',
        backgroundColor: '#F1F5F9',
    },
    chartToggleTextActive: {
        fontWeight: '600',
        fontSize: 13,
        color: 'white',
    },
    chartToggleTextInactive: {
        fontWeight: '600',
        fontSize: 13,
        color: '#64748B',
    },
    tooltipOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
    },
    transparentText: {
        color: 'transparent',
    },
    reflectionIconBg: {
        backgroundColor: '#EBF3F1',
    },
    reflectionValue: {
        fontSize: 18,
        marginVertical: 15,
        lineHeight: 30,
        paddingBottom: 5,
        flexWrap: 'wrap',
    },
    rotationalContainer: {
        backgroundColor: '#F8FAFC',
        padding: 15,
        borderRadius: 12,
        marginTop: 10,
    },
    rotationalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    rotationalLabel: {
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: theme.textSecondary,
    },
    rotationalScoreText: {
        color: '#F2994A',
        fontFamily: 'Inter_700Bold',
        fontSize: 12.5,
    },
    rotationalTrack: {
        width: '100%',
        backgroundColor: '#E2E8F0',
        height: 8,
        borderRadius: 4,
        overflow: 'hidden',
    },
    rotationalFill: {
        backgroundColor: '#F2994A',
        height: '100%',
        borderRadius: 4,
    },
    maslowActive: {
        backgroundColor: '#10B981',
    },
    maslowInactive: {
        backgroundColor: '#A0AEC0',
    },
    unmetNeedsTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 20,
        color: theme.text,
        marginBottom: 5,
    },
    unmetNeedsDesc: {
        fontFamily: 'Inter_400Regular',
        fontSize: 13,
        color: theme.textSecondary,
    },
    patternsContainer: {
        marginTop: 10,
    },
    needsImpactIconBg: {
        backgroundColor: 'rgba(242, 153, 74, 0.2)',
    },
    routineImpactIconBg: {
        backgroundColor: 'rgba(91, 141, 239, 0.2)',
    },
    stabilityIconBg: {
        backgroundColor: 'rgba(16, 185, 129, 0.2)',
    },
    riskBgHigh: { backgroundColor: 'rgba(239, 68, 68, 0.1)' },
    riskBgMed: { backgroundColor: 'rgba(245, 158, 11, 0.1)' },
    riskBgLow: { backgroundColor: 'rgba(16, 185, 129, 0.1)' },
    riskTextHigh: { color: '#EF4444' },
    riskTextMed: { color: '#F59E0B' },
    riskTextLow: { color: '#10B981' },
    riskFillHigh: { backgroundColor: '#EF4444' },
    riskFillMed: { backgroundColor: '#F59E0B' },
    riskFillLow: { backgroundColor: '#10B981' },
    iconRiskHigh: { color: '#EF4444' },
    iconRiskMed: { color: '#F59E0B' },
    iconRiskLow: { color: '#10B981' },
    iconBase16: { fontSize: 16 },
    iconBase12: { fontSize: 12 },
    iconBase10: { fontSize: 10 },
    iconSearchPlus: { fontSize: 16, color: '#7C9A92' },
    iconWarning: { color: '#EF4444' },
    iconSuccess: { color: '#10B981' },
    iconLarge: { fontSize: 60, color: '#7C9A92' },
    iconHeart: { fontSize: 16, color: '#EC4899' },
    iconUp: { color: '#10B981' },
    iconDown: { color: '#EF4444' },
    iconBrain: { fontSize: 16, color: '#7C9A92' },
    iconPie: { fontSize: 16, color: '#7C9A92' },
    iconScale: { fontSize: 16, color: '#F2994A' },
    iconCalendar: { fontSize: 16, color: '#5B8DEF' },
    iconWater: { fontSize: 16, color: theme.primary },
});
