import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../context/ThemeContext';

export const getStyles = (theme: ThemeColors) => StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.card,
    },
    keyboardView: {
        flex: 1,
    },
    mainContent: {
        flex: 1,
        backgroundColor: theme.card,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.03,
        shadowRadius: 20,
        elevation: 3,
        position: 'relative',
        overflow: 'hidden',
    },
    customHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.card,
        borderBottomWidth: 1,
        borderBottomColor: theme.border,
    },
    headerTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 18,
        color: theme.text,
    },
    homebrandText: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 19.2, // 1.2rem
        color: theme.text,
        marginLeft: 12,
    },
    welcomeSection: {
        padding: 24,
        alignItems: 'center',
        justifyContent: 'center',
        flexGrow: 1,
        paddingBottom: 120, // space for input wrapper
    },
    welcomeHeader: {
        alignItems: 'center',
        marginBottom: 40,
    },
    welcomeTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 28,
        color: theme.text,
        marginBottom: 10,
        textAlign: 'center',
    },
    welcomeSubtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 15,
        color: theme.textSecondary,
        textAlign: 'center',
    },
    actionGrid: {
        width: '100%',
        gap: 12,
    },
    actionCard: {
        backgroundColor: theme.card,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 12,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    cardContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    iconBox: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cardText: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 15,
        color: theme.text,
    },
    chatContainer: {
        flex: 1,
        marginBottom: 150, // space for input
    },
    messageBubble: {
        maxWidth: '85%',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 12,
        marginBottom: 15,
    },
    userMsg: {
        alignSelf: 'flex-end',
        backgroundColor: '#7C9A92',
        borderBottomRightRadius: 2,
    },
    botMsg: {
        alignSelf: 'flex-start',
        backgroundColor: '#EBF3F1',
        borderBottomLeftRadius: 2,
    },
    messageText: {
        fontFamily: 'Inter_400Regular',
        fontSize: 15.2,
        lineHeight: 22,
    },
    inputWrapper: {
        position: 'absolute',
        bottom: 40,
        left: 16,
        right: 16,
        backgroundColor: theme.card,
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 20,
        paddingHorizontal: 16,
        paddingVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.08,
        shadowRadius: 30,
        elevation: 5,
    },
    chatInput: {
        fontFamily: 'Inter_400Regular',
        fontSize: 16,
        color: theme.text,
        maxHeight: 100,
        minHeight: 24,
        marginBottom: 12,
    },
    inputFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: theme.border,
        paddingTop: 12,
    },
    attachments: {
        flexDirection: 'row',
    },
    attachBtn: {
        padding: 4,
    },
    sendBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#7C9A92',
        alignItems: 'center',
        justifyContent: 'center',
    },
    disclaimer: {
        position: 'absolute',
        bottom: 8,
        left: 16,
        right: 16,
        textAlign: 'center',
        fontFamily: 'Inter_400Regular',
        fontSize: 10,
        color: '#A0AEC0',
    },
    headerRightIcon: {
        width: 48,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 'auto',
    },
    rightDrawer: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        right: 0,
        width: 320,
        backgroundColor: theme.card,
        zIndex: 101,
        padding: 20,
        paddingTop: Platform.OS === 'ios' ? 50 : 20,
        shadowColor: '#000',
        shadowOffset: { width: -5, height: 0 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 10,
    },
    rightHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    rightHeaderTitle: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 18,
        color: theme.text,
    },
    searchWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.background,
        borderRadius: 8,
        paddingHorizontal: 12,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: theme.border,
    },
    searchInput: {
        flex: 1,
        height: 40,
        marginLeft: 8,
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: theme.text,
    },
    historyList: {
        flex: 1,
    },
    historyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: theme.background,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    historyIcon: {
        width: 32,
        height: 32,
        backgroundColor: theme.card,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        borderWidth: 1,
        borderColor: theme.border,
    },
    historyInfo: {
        flex: 1,
    },
    historyTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        color: theme.text,
        marginBottom: 4,
    },
    historyDate: {
        fontFamily: 'Inter_400Regular',
        fontSize: 12,
        color: theme.textSecondary,
    },
    dropdownMenu: {
        position: 'absolute',
        top: 30,
        right: 0,
        backgroundColor: theme.dangerBg,
        borderWidth: 1,
        borderColor: theme.dangerBorder,
        borderRadius: 8,
        padding: 12,
        flexDirection: 'row',
        alignItems: 'center',
        width: 105,
        zIndex: 1000,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
    },
    dropdownDanger: {
        fontFamily: 'Inter_500Medium',
        fontSize: 14,
        color: theme.danger,
    },
    noSessions: {
        alignItems: 'center',
        marginTop: 40,
    },
    noSessionsText: {
        fontFamily: 'Inter_400Regular',
        fontSize: 14,
        color: '#A0AEC0',
    },
    sessionEndedContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 30,
    },
    sessionEndedLine: {
        flex: 1,
        height: 1,
        backgroundColor: theme.border,
    },
    sessionEndedText: {
        paddingHorizontal: 15,
        fontSize: 14,
        fontFamily: 'Inter_500Medium',
        color: theme.textSecondary,
    },
    confirmActionContainer: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 15,
    },
    btnYes: {
        paddingVertical: 8,
        paddingHorizontal: 20,
        borderRadius: 8,
        backgroundColor: theme.danger,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnYesText: {
        color: theme.card,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
    },
    btnNo: {
        paddingVertical: 8,
        paddingHorizontal: 23,
        borderRadius: 8,
        backgroundColor: theme.text,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnNoText: {
        color: theme.card,
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
    }
});
