import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8FAFC', // Matching var(--bg-body)
    },
    mainContent: {
        flexGrow: 1,
        paddingHorizontal: 20,
        paddingTop: 30,
        paddingBottom: 40,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 30,
    },
    title: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 26,
        color: '#2D3748',
        marginBottom: 8,
    },
    subtitle: {
        fontFamily: 'Inter_400Regular',
        fontSize: 15,
        color: '#718096',
        lineHeight: 22,
    },
    profileContainer: {
        flexDirection: 'column',
        gap: 30,
    },
    profileHeaderCard: {
        borderRadius: 20, // var(--radius-xl)
        padding: 30,
        flexDirection: 'column',
        alignItems: 'center',
        gap: 20,
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.4)',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 30,
        elevation: 5,
    },
    avatarContainer: {
        position: 'relative',
        width: 120,
        height: 120,
        borderRadius: 60,
        backgroundColor: '#F8FAFC',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 4,
        borderColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 15,
        elevation: 4,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: 60,
    },
    editAvatarBtn: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: '#7C9A92', // var(--primary-sage)
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: '#FFFFFF',
        zIndex: 10,
    },
    profileInfo: {
        alignItems: 'center',
    },
    profileName: {
        fontFamily: 'Merriweather_700Bold',
        fontSize: 28,
        color: '#2D3748',
        marginBottom: 5,
    },
    profileEmail: {
        fontFamily: 'Inter_400Regular',
        fontSize: 16,
        color: '#718096',
        marginBottom: 15,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: '#D1FAE5',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 20,
    },
    statusBadgeText: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        color: '#059669',
    },
    profileDetailsCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 20, // var(--radius-xl)
        padding: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.05,
        shadowRadius: 30,
        elevation: 3,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    cardTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#E2E8F0',
        paddingBottom: 15,
        marginBottom: 20,
        gap: 10,
    },
    cardTitle: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 18,
        color: '#2D3748',
        flex: 1,
    },
    editBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#E2E8F0',
        backgroundColor: '#FFFFFF',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 2,
    },
    editBtnActive: {
        backgroundColor: '#7C9A92',
        borderColor: '#7C9A92',
    },
    editBtnText: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 14,
        color: '#2D3748',
    },
    editBtnTextActive: {
        color: '#FFFFFF',
    },
    editBtnGroup: {
        flexDirection: 'row',
        gap: 10,
    },
    detailsGrid: {
        flexDirection: 'column',
        gap: 20,
    },
    detailItem: {
        backgroundColor: '#F8FAFC',
        padding: 16,
        borderRadius: 12,
    },
    detailLabel: {
        fontFamily: 'Inter_600SemiBold',
        fontSize: 12,
        color: '#718096',
        marginBottom: 4,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    detailValue: {
        fontFamily: 'Inter_500Medium',
        fontSize: 16,
        color: '#2D3748',
    },
    inputField: {
        fontFamily: 'Inter_500Medium',
        fontSize: 16,
        color: '#2D3748',
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 4,
        paddingHorizontal: 10,
        paddingVertical: 8,
        width: '100%',
    },
    pickerContainer: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#E2E8F0',
        borderRadius: 4,
        overflow: 'hidden',
    },
    loadingText: {
        fontFamily: 'Inter_500Medium',
        fontSize: 15,
        color: '#718096',
        textAlign: 'center',
        paddingVertical: 40,
    },
    dropdownInput: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E2E8F0', borderRadius: 4, paddingHorizontal: 10, paddingVertical: 10 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.3)', justifyContent: 'flex-end' },
    modalContent: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingHorizontal: 20, paddingBottom: 40, maxHeight: '80%', borderWidth: 2, borderColor: '#E2E8F0' },
    modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#E2E8F0', marginBottom: 8 },
    modalTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 18, color: '#2D3748' },
    dropdownItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#F7FAFC' },
    dropdownItemSelected: { backgroundColor: '#F0F5F4', borderRadius: 8, paddingHorizontal: 12 },
    dropdownItemText: { fontFamily: 'Inter_400Regular', fontSize: 16, color: '#4A5568' },
    dropdownItemTextSelected: { fontFamily: 'Inter_600SemiBold', color: '#7C9A92' }
});
